# Generated by Django 4.2.30 on 2026-05-12 19:55

from django.db import migrations, models
import photos.models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Хэш файла'),
        ),
        migrations.AddField(
            model_name='photo',
            name='pixel_hash',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Хэш пикселей'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos/%Y/%m/', validators=[photos.models.validate_image_size]),
        ),
    ]
