# Generated by Django 4.2.30 on 2026-05-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0003_photo_file_hash_photo_pixel_hash_alter_photo_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="climate_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
