# Generated by Django 4.2.30 on 2026-05-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0004_photo_climate_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="file_size",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="Размер файла"
            ),
        ),
    ]
