# Generated by Django 4.2.30 on 2026-05-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0006_sitesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="is_public",
            field=models.BooleanField(default=False, verbose_name="Публичное фото"),
        ),
    ]
